source 'https://rubygems.org'
gem 'rails', '6.1.7.1'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0.8'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2.2'
gem 'jquery-rails', '>= 4.0.1'
gem 'turbolinks'
gem 'jbuilder', '~> 1.5', '>= 1.5.3'

gem 'binding_of_caller'
gem 'better_errors'
gem 'pry-rails'
gem 'puma', '>= 2.12.0'
