source 'https://rubygems.org'
gem 'rails', '6.1.7.3'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0.8'
gem 'uglifier', '>= 2.7.2'
gem 'coffee-rails', '~> 4.2.2'
gem 'jquery-rails', '>= 4.4.0'
gem 'turbolinks', '>= 5.0.0'
gem 'jbuilder', '~> 1.5', '>= 1.5.3'

gem 'binding_of_caller'
gem 'better_errors', '>= 2.8.0'
gem 'pry-rails'
gem 'puma', '>= 4.3.12'
